
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Dec 02 12:39:32 CET 2017
//----------------------------------------------------

package net.darmo_creations.scripting;

/** CUP generated class containing symbol constants. */
public class Tokens {
  /* terminals */
  public static final int CIRCUM_EQ = 50;
  public static final int STAR_EQ = 44;
  public static final int EXCL_EQ = 37;
  public static final int LBRACKET = 18;
  public static final int SLASH = 25;
  public static final int KW_FOR = 7;
  public static final int LPAREN = 16;
  public static final int DOUBLE_AND = 29;
  public static final int MINUS = 23;
  public static final int TILDE = 33;
  public static final int STAR = 24;
  public static final int RPAREN = 17;
  public static final int AND = 31;
  public static final int TILDE_EQ = 49;
  public static final int KW_FUNCTION = 10;
  public static final int COMMA = 15;
  public static final int PLUS = 22;
  public static final int ID = 52;
  public static final int LANGLE_EQ = 40;
  public static final int KW_CONTINUE = 9;
  public static final int EXCL = 28;
  public static final int KW_RETURN = 11;
  public static final int EOF = 0;
  public static final int RBRACKET = 19;
  public static final int error = 1;
  public static final int KW_UNTIL = 6;
  public static final int DOUBLE_STAR = 27;
  public static final int LCURLY = 20;
  public static final int PERCENT = 26;
  public static final int PIPE = 32;
  public static final int DOUBLE_EQ = 36;
  public static final int SEMI_COLON = 13;
  public static final int NUMBER = 51;
  public static final int EQ = 35;
  public static final int KW_IF = 3;
  public static final int RCURLY = 21;
  public static final int KW_NULL = 12;
  public static final int SLASH_EQ = 45;
  public static final int COLON = 14;
  public static final int KW_LET = 2;
  public static final int LANGLE = 38;
  public static final int AND_EQ = 47;
  public static final int KW_BREAK = 8;
  public static final int RANGLE = 39;
  public static final int KW_ELSE = 4;
  public static final int DOUBLE_PIPE = 30;
  public static final int STRING = 53;
  public static final int PLUS_EQ = 42;
  public static final int CIRCUMFLEX = 34;
  public static final int MINUS_EQ = 43;
  public static final int KW_WHILE = 5;
  public static final int PIPE_EQ = 48;
  public static final int PERCENT_EQ = 46;
  public static final int RANGLE_EQ = 41;
}

